# For more information go to : https://laravel.com/docs/sail
version: "3"
services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.0/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      CHOKIDAR_USEPOLLING: "true"
      HOST: 0.0.0.0
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - pgsql
  web:
    build: ./frontend
    container_name: movie_night_ui
    env_file: ./frontend/.env
    ports:
      - "8080:8080"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/src:z
      - ./frontend:/app:cached
    working_dir: /app
    networks:
      - sail
  pgsql:
    image: postgres:13
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "sailpgsql:/var/lib/postgresql/data"
    networks:
      - sail
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}",
        ]
networks:
  sail:
    driver: bridge
volumes:
  sailpgsql:
    driver: local
